name: Release

on: 
  push:
    tags:
      - '*.*.*'
    ignore-branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: |
        cd src/ 
        dotnet build --configuration Release
    - name: pack the nuget
      run: |
        cd src/
        dotnet pack --configuration Release
    - name: release package
      run: dotnet nuget push **/*.nupkg --api-key ${{secrets.nuget}} --source https://api.nuget.org/v3/index.json
